### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by ROMmonkey** [AntoPISA/MAME_SnapTitles#2]
Hello

The way you distribute your snaps is a bit unhandy and slow.

- Downloading snaps from github is difficult because we need to download them all at once (downloading the files manually for'missing files or updated files takes too much time).
It's also not recommeded to flood github with thousands of binary files (images) since github's goal is to host text files (code) on which a diff can be done. I'm not sure if you violate github's policy with this. 

- Downloading snaps on your website also forces us to download all packages again even if we just need some missing or updated snaps. Sometimes you package everything again and then we need to download the entire snap collection

So how to solve this?
I would recommend using FTP server with a folder for each kind of snaps (boss, title, ...) so we can select all missing/updated files as reported by our rommanager and then just download only these files. No need to download everything over and over again.
You just overwrite the files on the FTP server to keep it up to,date. In addition we can see the new changed dates of the files on the FTP server. We can even download the latest updates from the FTP server by just looking at the date of the files without even using a rommanager.

**Comment by AntoPISA** [comment]
The files currently present here are for experimental purposes only, for the use and consumption of a third-party program.  My files will be released on my site with the methods used thus far.

**Comment by seleuco** [comment]
The porpouse of git is store, **tracking**, and **collaborating** on software projects. It is not a software distribution mechanism although it can be useful in this aspect through the concept of release where you can publish different packages attached to the release.
